version: "3"

x-common: &common
  working_dir: /service
  tty: true
  expose:
    - 8080
  command: python main.py

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf:/etc/nginx/vhost.d
    depends_on:
      - service1
      - service2
      - service3

  termination:
    image: containous/whoami:latest
    environment:
      - VIRTUAL_HOST=localhost

  service1:
    <<: *common
    build:
      context: "./service1"
    volumes:
      - ./service1:/service

  service2:
    <<: *common
    build:
      context: "./service2"
    volumes:
      - ./service2:/service

  service3:
    <<: *common
    build:
      context: "./service3"
    volumes:
      - ./service3:/service
