version: "3"

x-common: &common
  working_dir: /service
  tty: true
  expose:
    - 8080
  command: python main.py

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf:/etc/nginx/vhost.d
    depends_on:
      - serviceA
      - serviceB
      - serviceC

  termination:
    image: containous/whoami
    environment:
      - VIRTUAL_HOST=localhost

  serviceA:
    <<: *common
    build:
      context: "./serviceA"
    volumes:
      - ./serviceA:/service

  serviceB:
    <<: *common
    build:
      context: "./serviceB"
    volumes:
      - ./serviceB:/service

  serviceC:
    <<: *common
    build:
      context: "./serviceC"
    volumes:
      - ./serviceC:/service
