version: "3"

x-common: &common
  working_dir: /service
  tty: true
  command: [python, main.py]

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    # "ホストのポート:nginxコンテナのポート"を接続。（例：ホストの##番ポートへのリクエストは、nginxコンテナ内の**番に転送。）
    ports:
      - "5000:80"
    volumes:
      # ソケット通信を行うためのDockerのソケットパス
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # confファイルをnginxに利用
      - ./conf:/etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - service1
      - service2

  # gateway
  termination:
    image: containous/whoami
    environment:
      - VIRTUAL_HOST=localhost

  # service1という名前のサービスのDockerイメージをビルド
  service1:
    <<: *common
    # Docker build時にコンテナにコピーしたいローカルファイルの場所. ymlファイルの場所をカレントディレクトリとしている.
    build:  ./service1
    # コンテナにマウント
    volumes:
      - ./service1:/service

  service2:
    <<: *common
    build:  ./service2
    volumes:
      - ./service2:/service

  service3:
    <<: *common
    build: ./service3
    volumes:
      - ./service3:/service
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
      - FLASK_APP=./service3/main.py
    depends_on:
      - "db"

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/log/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 5001:5001
