version: "3"

x-common: &common
  working_dir: /service
  tty: true
  command: [python, main.py]

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    # "ホストのポート:コンテナのポート"を接続。（例：ホストの5000番ポートへのリクエストは、プロキシのコンテナ内の5000番に転送。）
    ports:
      - "5000:80"
    volumes:
      # ソケット通信を行うためのDockerのソケットパス
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # confファイルをnginxに利用
      - ./conf:/etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - service1
      - service2
      - service3

  # gateway
  termination:
    image: containous/whoami
    environment:
      - VIRTUAL_HOST=localhost

  # service1という名前のサービスのDockerイメージをビルド
  service1:
    <<: *common
    # Docker build時にコンテナにコピーしたいローカルファイルの場所. ymlファイルの場所をカレントディレクトリとしている.
    build:  ./service1
    # コンテナにマウント
    volumes:
      - ./service1:/service

  service2:
    <<: *common
    build:  ./service2
    volumes:
      - ./service2:/service

  service3:
    <<: *common
    build:  ./service3
    volumes:
      - ./service3:/service
