version: "3"

x-common: &common
  working_dir: /service
  tty: true
  command: python main.py

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    # ホストのポートとコンテナのポートを接続。（例：ホストの5000番ポートへのリクエストは、プロキシのコンテナ内の5000番に転送。）
    ports:
      - "5000:80"
      # - "443:443"
    volumes:
      # ソケット通信を行うためのDockerのソケットパス
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # confファイルをnginxに利用
      - ./conf:/etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - service1
      - service2
      - service3

  termination:
    image: containous/whoami
    environment:
      - VIRTUAL_HOST=localhost
    ports:
    - "5000:80"

  # service1という名前のサービスのDockerイメージをビルド
  service1:
    <<: *common
    build:
      # Docker build時にコンテナにコピーしたいローカルファイルの場所. ymlファイルの場所をカレントディレクトリとしている.
      context: "./service1"
    # コンテナにマウント
    volumes:
      - ./service1:/service

  service2:
    <<: *common
    build:
      context: "./service2"
    volumes:
      - ./service2:/service

  service3:
    <<: *common
    build:
      context: "./service3"
    volumes:
      - ./service3:/service
