FROM python:3.9.5-alpine
WORKDIR /app
COPY requirements.txt .
RUN apk --no-cache add build-base libffi-dev openssl-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del build-base libffi-dev openssl-dev \
    pip install flask, render_template

COPY . .

EXPOSE 5000

CMD ["python", "-B", "run.py"]