FROM python:alpine

RUN apk --no-cache add build-base libffi-dev openssl-dev &&
RUN pip install --no-cache-dir -r requirements.txt &&
RUN apk del build-base libffi-dev openssl-dev
RUN pip install SQLAlchemy
RUN pip install Flask
RUN pip install flask_sqlalchemy

WORKDIR /app

COPY . /app

EXPOSE 5000

CMD ["python", "main.py"]
